
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.Timer;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hamil
 */
public class Diseño_de_sistemas extends javax.swing.JFrame {

	/**
 	* Creates new form Diseño_de_sistemas
 	*/

    
//	Instancias
//	Loogin ins = new Loogin();
	Date hora = new Date();
    
	//	Variables
	private Timer cronometro;
	int seg,hor,min;
	boolean[] press = new boolean[5];
	int[] botones = new int[3];
    
    
	public Diseño_de_sistemas() {
    	initComponents();
    	PAUSED.setVisible(true);
        	RESUMEN.setVisible(false);
        	setLocationRelativeTo(null);
//        	User.setText(String.valueOf(ins.instancia.User));
                Current_time_hour.setText("ejemplo");	}

	/**
 	* This method is called from within the constructor to initialize the form.
 	* WARNING: Do NOT modify this code. The content of this method is always
 	* regenerated by the Form Editor.
 	*/
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                     	 
	private void initComponents() {

    	jRadioButton1 = new javax.swing.JRadioButton();
    	jLabel1 = new javax.swing.JLabel();
    	jLabel2 = new javax.swing.JLabel();
    	jButton3 = new javax.swing.JButton();
    	jButton4 = new javax.swing.JButton();
    	jButton5 = new javax.swing.JButton();
    	jButton6 = new javax.swing.JButton();
    	HANGUP = new javax.swing.JButton();
    	jButton8 = new javax.swing.JButton();
    	jTextField1 = new javax.swing.JTextField();
    	jLabel3 = new javax.swing.JLabel();
    	jLabel4 = new javax.swing.JLabel();
    	jLabel5 = new javax.swing.JLabel();
    	jLabel6 = new javax.swing.JLabel();
    	jLabel7 = new javax.swing.JLabel();
    	jLabel8 = new javax.swing.JLabel();
    	jLabel9 = new javax.swing.JLabel();
    	jTextField3 = new javax.swing.JTextField();
    	jLabel10 = new javax.swing.JLabel();
    	jTextField5 = new javax.swing.JTextField();
    	jLabel11 = new javax.swing.JLabel();
    	jTextField6 = new javax.swing.JTextField();
    	jTextField7 = new javax.swing.JTextField();
    	jTextField8 = new javax.swing.JTextField();
    	Timer = new javax.swing.JLabel();
    	jScrollPane1 = new javax.swing.JScrollPane();
    	jTextArea1 = new javax.swing.JTextArea();
    	Current_time_hour = new javax.swing.JLabel();
    	Channel_of_call = new javax.swing.JLabel();
    	Current_time_min = new javax.swing.JLabel();
    	Current_time_seg = new javax.swing.JLabel();
    	jLabel15 = new javax.swing.JLabel();
    	jLabel16 = new javax.swing.JLabel();
    	Horario = new javax.swing.JLabel();
    	SECONDPHONE = new javax.swing.JButton();
    	MAINPHONE = new javax.swing.JButton();
    	THIRDPHONE = new javax.swing.JButton();
    	PHONE = new javax.swing.JLabel();
    	PAUSED = new javax.swing.JLabel();
    	RESUMEN = new javax.swing.JLabel();
    	User = new javax.swing.JLabel();

    	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    	setBackground(new java.awt.Color(49, 26, 26));
    	setForeground(new java.awt.Color(25, 25, 25));

    	jRadioButton1.setText("ALT PHONE DIAL");

    	jLabel1.setText("RECORDING FILE");

    	jLabel2.setText("RECORD ID");

    	jButton3.setText("START RECORDING");
    	jButton3.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jButton3ActionPerformed(evt);
        	}
    	});

    	jButton4.setText("WED FORM");

    	jButton5.setText("PARK CALL");

    	jButton6.setText("TRANFERS - CONF");

    	HANGUP.setBackground(new java.awt.Color(187, 204, 196));
    	HANGUP.setText("HANGUP CUSTOMER");
    	HANGUP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    	HANGUP.setRequestFocusEnabled(false);
    	HANGUP.setRolloverEnabled(false);
    	HANGUP.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
            	HANGUPActionPerformed(evt);
        	}
    	});

    	jButton8.setText("SEND DTMF");

    	jTextField1.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jTextField1ActionPerformed(evt);
        	}
    	});

    	jLabel3.setText("DIALER desktop version 0.1 By Hamil");

    	jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
    	jLabel4.setText("STATUS:");

    	jLabel5.setFont(new java.awt.Font("Cantarell", 3, 24)); // NOI18N
    	jLabel5.setIcon(new javax.swing.ImageIcon("/home/hamil/Pictures/dialer-icon.png")); // NOI18N
    	jLabel5.setText("DIALER");

    	jLabel6.setText("CHANNEL:");

    	jLabel7.setText("CUSTOMER TIME:");

    	jLabel8.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
    	jLabel8.setText("Customer Information:");

    	jLabel9.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
    	jLabel9.setText("FIRST:");

    	jTextField3.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jTextField3ActionPerformed(evt);
        	}
    	});

    	jLabel10.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
    	jLabel10.setText("LAST:");

    	jLabel11.setBackground(new java.awt.Color(114, 84, 84));
    	jLabel11.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
    	jLabel11.setForeground(new java.awt.Color(110, 43, 151));
    	jLabel11.setText("10 ACTIVE CALLBACKS");

    	Timer.setBackground(new java.awt.Color(151, 120, 120));
    	Timer.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N

    	jTextArea1.setColumns(20);
    	jTextArea1.setRows(5);
    	jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
            	jTextArea1MouseClicked(evt);
        	}
    	});
    	jScrollPane1.setViewportView(jTextArea1);

    	Current_time_hour.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N

    	Channel_of_call.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N

    	Current_time_min.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N

    	Current_time_seg.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N

    	jLabel15.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
    	jLabel15.setText(":");

    	jLabel16.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
    	jLabel16.setText(":");

    	SECONDPHONE.setText("SECOND PHONE");
    	SECONDPHONE.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
            	SECONDPHONEActionPerformed(evt);
        	}
    	});

    	MAINPHONE.setText("MAIN PHONE");
    	MAINPHONE.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
            	MAINPHONEActionPerformed(evt);
        	}
    	});

    	THIRDPHONE.setText("THIRD PHONE");
    	THIRDPHONE.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
            	THIRDPHONEActionPerformed(evt);
        	}
    	});

    	PHONE.setFont(new java.awt.Font("Mukti Narrow", 1, 12)); // NOI18N

    	PAUSED.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
    	PAUSED.setText("PAUSED");

    	RESUMEN.setFont(new java.awt.Font("Cantarell", 1, 14)); // NOI18N
    	RESUMEN.setText("RESUME");

    	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    	getContentPane().setLayout(layout);
    	layout.setHorizontalGroup(
        	layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        	.addGroup(layout.createSequentialGroup()
            	.addContainerGap()
            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                	.addGroup(layout.createSequentialGroup()
                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        	.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            	.addComponent(HANGUP, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            	.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
                        	.addGroup(layout.createSequentialGroup()
                            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                	.addGroup(layout.createSequentialGroup()
                                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            	.addGroup(layout.createSequentialGroup()
                                                	.addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                	.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                	.addGap(11, 11, 11))
                                            	.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                	.addGap(61, 61, 61)
                                                	.addComponent(PAUSED)
                                                	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                	.addComponent(RESUMEN)))
                                        	.addGroup(layout.createSequentialGroup()
                                            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                	.addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                	.addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            	.addGap(17, 17, 17)))
                                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        	.addGroup(layout.createSequentialGroup()
                                            	.addGap(133, 133, 133)
                                            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                	.addGroup(layout.createSequentialGroup()
                                                    	.addGap(12, 12, 12)
                                                    	.addComponent(MAINPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                	.addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            	.addGap(388, 388, 388)
                                            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                	.addGroup(layout.createSequentialGroup()
                                                    	.addGap(12, 12, 12)
                                                    	.addComponent(THIRDPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                	.addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        	.addGroup(layout.createSequentialGroup()
                                            	.addGap(487, 487, 487)
                                            	.addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            	.addGap(18, 18, 18)
                                            	.addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        	.addGroup(layout.createSequentialGroup()
                                            	.addGap(399, 399, 399)
                                            	.addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    	.addGroup(layout.createSequentialGroup()
                                        	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            	.addGroup(layout.createSequentialGroup()
                                                	.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                	.addGap(49, 49, 49)
                                                	.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            	.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            	.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            	.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            	.addGroup(layout.createSequentialGroup()
                                                	.addGap(134, 134, 134)
                                                	.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            	.addGroup(layout.createSequentialGroup()
                                                	.addGap(203, 203, 203)
                                                	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    	.addGroup(layout.createSequentialGroup()
                                                        	.addGap(12, 12, 12)
                                                        	.addComponent(PHONE, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        	.addComponent(Timer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        	.addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        	.addComponent(SECONDPHONE, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    	.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    	.addGroup(layout.createSequentialGroup()
                                        	.addGap(399, 399, 399)
                                        	.addComponent(Current_time_hour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        	.addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        	.addComponent(Current_time_min, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        	.addGap(7, 7, 7)
                                        	.addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        	.addComponent(Current_time_seg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        	.addComponent(Horario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        	.addGap(238, 238, 238)
                                        	.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        	.addComponent(Channel_of_call, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    	.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        	.addComponent(jRadioButton1)
                                        	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        	.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        	.addGap(18, 18, 18)
                                        	.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        	.addGap(402, 402, 402))))
                            	.addGap(0, 0, Short.MAX_VALUE)))
                    	.addContainerGap(72, Short.MAX_VALUE))
                	.addGroup(layout.createSequentialGroup()
                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        	.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        	.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    	.addGap(0, 0, Short.MAX_VALUE))))
        	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            	.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                	.addContainerGap(482, Short.MAX_VALUE)
                	.addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                	.addContainerGap(529, Short.MAX_VALUE)))
    	);
    	layout.setVerticalGroup(
        	layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
        	.addGroup(layout.createSequentialGroup()
            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                	.addGroup(layout.createSequentialGroup()
                    	.addGap(32, 32, 32)
                    	.addComponent(Channel_of_call, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    	.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    	.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    	.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                	.addGroup(layout.createSequentialGroup()
                    	.addGap(31, 31, 31)
                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        	.addComponent(Current_time_min, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        	.addComponent(Current_time_seg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                        	.addComponent(Current_time_hour, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        	.addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        	.addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        	.addComponent(Horario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            	.addGap(37, 37, 37)
            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                	.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                	.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                	.addComponent(PAUSED, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                	.addComponent(RESUMEN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                	.addGroup(layout.createSequentialGroup()
                    	.addGap(23, 23, 23)
                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        	.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        	.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        	.addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        	.addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                	.addGroup(layout.createSequentialGroup()
                    	.addGap(18, 18, 18)
                    	.addComponent(jRadioButton1)))
            	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            	.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            	.addGap(18, 18, 18)
            	.addComponent(jLabel2)
            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                	.addGroup(layout.createSequentialGroup()
                    	.addGap(5, 5, 5)
                    	.addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    	.addComponent(SECONDPHONE)
                    	.addGap(0, 0, 0)
                    	.addComponent(Timer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            	.addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            	.addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            	.addComponent(jButton5))
                        	.addComponent(PHONE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    	.addGap(7, 7, 7))
                	.addGroup(layout.createSequentialGroup()
                    	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    	.addComponent(jButton3)
                    	.addGap(18, 18, 18)
                    	.addComponent(jButton4)))
            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                	.addGroup(layout.createSequentialGroup()
                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        	.addComponent(THIRDPHONE)
                        	.addComponent(MAINPHONE))
                    	.addGap(18, 18, 18)
                    	.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                	.addGroup(layout.createSequentialGroup()
                    	.addGap(11, 11, 11)
                    	.addComponent(jButton6)
                    	.addGap(30, 30, 30)
                    	.addComponent(HANGUP)
                    	.addGap(55, 55, 55)
                    	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        	.addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        	.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            	.addGap(32, 32, 32)
            	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                	.addGroup(layout.createSequentialGroup()
                    	.addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    	.addContainerGap())
                	.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    	.addGap(0, 0, Short.MAX_VALUE)
                    	.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))))
        	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            	.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                	.addContainerGap(306, Short.MAX_VALUE)
                	.addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                	.addContainerGap(322, Short.MAX_VALUE)))
    	);

    	pack();
	}// </editor-fold>                   	 

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                       	 
    	// TODO add your handling code here:
	}                                      	 

	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                       	 
    	// TODO add your handling code here:
	}                                      	 

	public class tiempo implements ActionListener
	{

    	@Override
    	public void actionPerformed(ActionEvent e) {
        	GregorianCalendar calendario = new GregorianCalendar();
        	int seg1 = calendario.get(Calendar.SECOND),min1 = calendario.get(Calendar.MINUTE), hor1 = calendario.get(Calendar.HOUR_OF_DAY);
       	 

       	 
            	seg++;
            	if(min == 60)
            	{
                	hor++;
                	min = 0;
            	}
            	else
            	{
                	if(seg == 60)
                	{
                    	min++;
                    	seg=0;
                   	 
                	}
            	}
            	Timer.setText("   	"+hor+":"+min+":"+seg);
        	Current_time_hour.setText(String.valueOf(hor1));
                Current_time_min.setText(String.valueOf(min1));
                Current_time_seg.setText(String.valueOf(seg1));
    	Channel_of_call.setText("CLARO-DOMINICAN-PRIVILEGE");}
    	}
   	 
    
	private void HANGUPActionPerformed(java.awt.event.ActionEvent evt) {                                  	 
        	MAINPHONE.setBackground(Color.LIGHT_GRAY);
        	SECONDPHONE.setBackground(Color.LIGHT_GRAY);
        	THIRDPHONE.setBackground(Color.LIGHT_GRAY);
        	HANGUP.setBackground(Color.LIGHT_GRAY);
        	hor = 0;
        	min =0;
        	seg =0;
        	Timer.setText("   	"+hor+":"+min+":"+seg);
        	cronometro.stop();
        	MAINPHONE.setVisible(true);
    	SECONDPHONE.setVisible(true);
    	THIRDPHONE.setVisible(true);
       	 
        	RESUMEN.setVisible(false);
        	PAUSED.setVisible(true);
       	 
   	 
   	 
  	 
	}                                 	 

	private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {                                   	 
   	cronometro = new Timer(1000, new tiempo());
   	HANGUP.setBackground(Color.red);
    	cronometro.start();
	}                                  	 

	private void SECONDPHONEActionPerformed(java.awt.event.ActionEvent evt) {                                       	 
    	SECONDPHONE.setBackground(Color.DARK_GRAY);
    	MAINPHONE.setVisible(false);
    	SECONDPHONE.setVisible(false);
    	THIRDPHONE.setVisible(false);
    	cronometro = new Timer(1000, new tiempo());
    	PHONE.setText("  	SECOND - PHONE");
  	HANGUP.setBackground(Color.red);
    	cronometro.start();
   	 
     	if(botones[1] >= 1 &&  !press[3])
    	{
        	PAUSED.setVisible(false);
        	RESUMEN.setVisible(true);
       	}
   	 
    	else
    	{
            if(botones[1] < 1 && !press[3])
    	{
                PAUSED.setVisible(false);
        	RESUMEN.setVisible(true);
       	}
   	 
    	}
       	botones[1]++;
	}                                      	 

	private void MAINPHONEActionPerformed(java.awt.event.ActionEvent evt) {                                     	 
    	MAINPHONE.setBackground(Color.DARK_GRAY);
    	MAINPHONE.setVisible(false);
    	SECONDPHONE.setVisible(false);
    	THIRDPHONE.setVisible(false);
    	cronometro = new Timer(1000, new tiempo());
    	HANGUP.setBackground(Color.red);
    	PHONE.setText("      	MAIN - PHONE");
    	cronometro.start();
   	PAUSED.setVisible(false);
        RESUMEN.setVisible(true);
   	}                                    	 

	private void THIRDPHONEActionPerformed(java.awt.event.ActionEvent evt) {                                      	 
    	THIRDPHONE.setBackground(Color.DARK_GRAY);
    	MAINPHONE.setVisible(false);
    	SECONDPHONE.setVisible(false);
    	THIRDPHONE.setVisible(false);
    	cronometro = new Timer(1000, new tiempo());
    	HANGUP.setBackground(Color.red);
    	PHONE.setText("   	THIRD - PHONE");
    	cronometro.start();
    	if(botones[2] >= 1 &&  !press[3])
    	{
                PAUSED.setVisible(false);
        	RESUMEN.setVisible(true);
    	}
   	 
    	else
    	{
     	if(botones[2] < 1 && !press[3])
    	{
        	PAUSED.setVisible(false);
        	RESUMEN.setVisible(true);
       	}
   	 
    	}
       	botones[2]++;
	}                                     	 

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                    	 
    	// TODO add your handling code here:
	}                                   	 

	/**
 	* @param args the command line arguments
 	*/
	public static void main(String args[]) {
    	/* Set the Nimbus look and feel */
    	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     	* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     	*/
    	try {
        	for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            	if ("Nimbus".equals(info.getName())) {
                	javax.swing.UIManager.setLookAndFeel(info.getClassName());
                	break;
            	}
        	}
    	} catch (ClassNotFoundException ex) {
        	java.util.logging.Logger.getLogger(Diseño_de_sistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    	} catch (InstantiationException ex) {
        	java.util.logging.Logger.getLogger(Diseño_de_sistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    	} catch (IllegalAccessException ex) {
        	java.util.logging.Logger.getLogger(Diseño_de_sistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
        	java.util.logging.Logger.getLogger(Diseño_de_sistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    	}
    	//</editor-fold>

    	/* Create and display the form */
    	java.awt.EventQueue.invokeLater(new Runnable() {
        	public void run() {
            	new Diseño_de_sistemas().setVisible(true);
        	}
    	});
	}

	// Variables declaration - do not modify                	 
	private javax.swing.JLabel Channel_of_call;
	private javax.swing.JLabel Current_time_hour;
	private javax.swing.JLabel Current_time_min;
	private javax.swing.JLabel Current_time_seg;
	private javax.swing.JButton HANGUP;
	private javax.swing.JLabel Horario;
	private javax.swing.JButton MAINPHONE;
	private javax.swing.JLabel PAUSED;
	private javax.swing.JLabel PHONE;
	private javax.swing.JLabel RESUMEN;
	private javax.swing.JButton SECONDPHONE;
	private javax.swing.JButton THIRDPHONE;
	private javax.swing.JLabel Timer;
	private javax.swing.JLabel User;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton8;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	// End of variables declaration              	 
}



